# Generated by Django 5.2.1 on 2025-05-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ReserVou", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="status",
            field=models.CharField(
                choices=[("ativa", "Ativa"), ("cancelada", "Cancelada")],
                default="ativa",
                max_length=20,
            ),
        ),
    ]
