# Generated by Django 5.2.1 on 2025-06-16 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ReserVou", "0002_reserva_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="nome",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cliente",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="nome",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hotel",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
