# Generated by Django 5.2.3 on 2025-06-20 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ReserVou", "0003_gerente_hotel_gerente"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gerente",
            old_name="usuario",
            new_name="nome",
        ),
    ]
